#!/bin/sh

ACT_DIR=${HOME}/.act

# --------------------------------------
# Check pre-requirements
# --------------------------------------
if [ $(which brew) = "" ]; then
  echo "Homebrew is not installed"
  exit 1
fi
_installed_python=`brew list python3 > /dev/null`
if [[ $_installed_python -ne 0 ]]; then
  echo "Python3 is not installed"
  brew install python3
fi
if [ $(which git) = "" ]; then
  echo "Git is not installed"
  brew install git
fi

# --------------------------------------
# Check and create working directory
# --------------------------------------
if [ ! -d "$ACT_DIR" ]; then
  :
elif [ ! -e "$ACT_DIR/bin/act" ]; then
  echo "Act working directory is not used as act"
  echo "If install act, remove directory '$ACT_DIR'"
  exit 1
else
  echo "Act is already installed."
  exit 0
fi

# --------------------------------------
# Install act
# --------------------------------------
echo "Start installation act"
git clone https://github.com/attakei/act.git $ACT_DIR
python3 -m venv $ACT_DIR/.venv
